config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about" , as: "about"
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
   resource :favorites, only: [:create, :destroy]
   
   resources :book_comments, only: [:create, :destroy]
  end
  
    resources :users, only: [:show, :new, :create, :edit, :update, :index] do
        # フォロー機能追加に伴い以下3行追加
      resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user

has_many :favorites, dependent: :destroy
has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

validates :title, presence: true
validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, length: { minimum: 1}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comment, dependent: :destroy

  attachment :profile_image
  
  # フォローしているユーザとのアソシエイト
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  # 
  
  # フォローされているユーザーとのアソシエイト
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  # 
  # ユーザーをフォローする時既にフォローしていないか
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
  # 
  
  validates :name, presence: true, uniqueness: true, length:{ minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top,:about]


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end


  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
      devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
    end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.book_id = book.id
    comment.user_id = current_user.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment .find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(@book)
  end

  private
    def book_comment_params
      params.require(:book_comment).permit(:comment)

    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController



  def index
    @books = Book.all
    @book = Book.new
    @user = current_user

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id)
    flash[:create] = 'You have created book successfully.'
    else
    @books = Book.all
    @user = current_user
    render :index
    end
  end



  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
     @book.destroy
    redirect_to books_path

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:update] = 'You have updated book successfully.'
    else
      render :edit

    end

  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_back(fallback_location: root_path)

  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top

  end

  def about

  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        follow = current_user.active_relationships.build(follower_id: params[:user_id])
        follow.save
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
        follow.destroy
        redirect_back(fallback_location: root_path)
    end
    
    def followings
    user = User.find(params[:user_id])
    @users = user.followings
    end
    
    def followers
    user = User.find(params[:user_id])
    @users = user.followers
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id)
    flash[:create] = 'You have created book successfully.'
    else
    @books = Book.all
    render :index
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end


  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:update] = "You have updated user successfully."
    else
      render :edit
    end
  end
  
  
  def follows
    user = User.find(params[:id])
    @users = user.followers
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
    <div class="container px-5 px-sm-0">
      <div>
        <% if book.errors.any? %>
        <div class="error">
         <%= book.errors.count %>errors prohibited this obj from being saved:
         <% book.errors.full_messages.each do |message| %>
         <ul>
             <li>
                 <%= message %>
             </li>
         </ul>
        <% end %>
        <% end %>
        </div>

app/views/books/_list.html.erb
      <div class="row">
        <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill,100,100,format: 'jpeg', fallback:"no_image.jpg" %>
         <table class="table">
           <tbody>
             <tr>
               <th>name</ty>
               <th><%= user.name %></th>
             </tr>
             <tr>
               <th>introduction</th>
               <th><%= user.introduction %></th>
             </tr>
           </tbody>
         </table>
         <div class="row">
           <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary' do %>
           <i class="fas fa-user-cog"></i>
           <% end %>
         </div>
         <h2 class="mt-3">New book</h2>
         <%= form_with model:new_book, local:true do |f| %>
         <div class="field">
             <label>Title</label><br>
             <%= f.text_field :title %>
         </div>
         <div class="field">
             <label>Opinion</label><br>
             <%= f.text_field :body %>
         </div>
         <div class="action">
         <%= f.submit 'Create Book', class: 'btn btn-success' %>
         <% end %>
         </div>
      </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
       <% if @book.errors.any? %>
        <div class="error">
         <%= @book.errors.count %>errors prohibited this book from being saved:
         <% @book.errors.full_messages.each do |message| %>
         <ul>
             <li>
                 <%= message %>
             </li>
         </ul>
          <% end %>
        <% end %>
        <%= form_with model:@book, local:true do |f| %>
        <div class="field">
         <label>Title</label><br>
         <%= f.text_field :title %>
        </div>
        <div class="field">
        <label>Opinion</label><br>
         <%= f.text_field :body %>
        </div>
        <div action="action">
         <%= f.submit 'Update Book', class: 'btn btn-success' %><br>
         <% end %>
         <%= link_to "Show", book_path(@book.id) %>
         |
         <%= link_to "Back", books_path %>
        </div>
       </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
      <%= render 'books/error',book: @book %>
      <%= render 'books/list',user: @user,new_book: @book %>

      <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
              <thead>
                  <tr>
                      <th></th>
                      <th>Title</th>
                      <th>Opinion</th>
                      <th colspan="3"></th>
                  </tr>
              </thead>
              <tbody>
                  <% @books.each do |book| %>
                    <tr>
                        <td>
                          <%= link_to user_path(book.user) do %>
                            <%= attachment_image_tag @user, :profile_image, size: '40x40', format: 'jpeg', fallback:"no_image.jpg" %>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to book.title,book_path(book.id) %>
                        </td>
                        <td><%= book.body %></td>
                        <!--いいね数表示-->
                        <td>
                          <% if book.favorited_by?(current_user) %>
                            <%= link_to book_favorites_path(book), method: :delete do %>
                            ♥<%= book.favorites.count %>
                            <% end %>
                          <% else %>
                            <%= link_to book_favorites_path(book), method: :post do %>
                              ♡<%= book.favorites.count %>
                            <% end %>
                          <% end %>
                        </td>
                        <!--コメント数表示-->
                        <td>コメント数<%= book.book_comments.count %></td>
                    </tr>
                  <% end %>
              </tbody>
          </table>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
  <p class="flash">
    <%= flash[:create] %>
    <%= flash[:update] %>
  </p>
      <%= render 'books/error',book: @book %>
      <%= render 'books/list',user: @user,new_book: @new_book %>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
              <tr>
                <td>
                  <%= link_to user_path do %>
                  <%= attachment_image_tag @user, :profile_image, size: '40x40', format: 'jpeg', fallback:"no_image.jpg" %><br>
                  <% end %>
                  <%= link_to user_path(@user) do %>
                  <%= @book.user.name %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path do %>
                  <%= @book.title %>
                  <% end %>
                </td>
                <td><%= @book.body %></td>
                <% if @book.user.id == current_user.id %>
                  <td><%= link_to "Edit", edit_book_path %></td>
                  <td><%= link_to "Destroy",book_path, method: :delete %></td>
                <% end %>
                <!--いいね機能-->
                <td>
                  <% if @book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    ♥<%= @book.favorites.count %>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      ♡<%= @book.favorites.count %>
                    <% end %>
                  <% end %>
                </td>
                <!--コメント数表示-->
                <td>
                  <p>コメント数:<%= @book.book_comments.count %></p>
                </td>
              </tr>
              <!--コメント一覧表示とコメント削除機能-->
            <table class="table">
              <% @book.book_comments.each do |book_comment| %>
              <tr>
                <td>
                  <%= link_to attachment_image_tag book_comment.user, :profile_image, size: '40x40', format: 'jpeg', fallback:"no_image.jpg" %><br>
                  <%= book_comment.user.name %>
                </td>
                <td>
                  <%= book_comment.comment %>
                </td>
                <td>
                  <% if book_comment.user_id == current_user.id %>
                  <%= link_to "Delete", book_book_comment_path(@book,book_comment.id),method: :delete %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </table>
            <!--コメント投稿フォーム-->
            <div class="new-comment">
                   <%= form_with(model:[@book,@book_comment],local:true) do |f| %>
                   <%= f.text_area :comment, rows:'5',placeholder:"コメント" %><br>
                   <%= f.submit "送信" %>
                   <% end %>
            </div>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/homes/about.html.erb
<h1>
  Welcome to
  <i class="fas fa-book"></i>
  <strong>
    Bookers
  </strong>
  !
</h1>

app/views/homes/top.html.erb
<%= notice %>
<h1>welome to
    <i class="fas fa-book"></i>
  <strong>Bookers

  </strong>
  !!
</h1>
<p>
  in
  <i class="fas fa-book"></i>
  <strong>
    Bookers
  </strong>
  ,
</p>

<p>you can share and exchange your opinions,inpressions,and emotions</p>
 <% if user_signed_in? %>
 <%= link_to "Log in", user_path(current_user) %><br>
 <%= link_to "Sign up", user_path(current_user) %>

 <% else %>
<%= link_to "Log in", new_user_session_path %> <br>
<%= link_to "Sign Up",new_user_registration_path %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
<table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th clspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag @user, :profile_image, size: '40x40', format: 'jpeg', fallback:"no_image.jpg" %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <!--フォロー数・フォロワー数表示とフォローするor外すの表示と機能-->
                <td>
                  フォロー数<%= user.followings.count %>
                </td>
                <td>
                  フォロワー数<%= user.followers.count %>
                </td>
                <td>
                  <% if current_user != user %>
                    <% if user.followed_by?(current_user) %>
                    <%= link_to "フォロー外す",user_relationships_path(user.id),method: :delete %>
                    <% else %>
                    <%= link_to "フォローする",user_relationships_path(user.id),method: :post %>
                    <% end %>
                  <% end %>
                </td>
                <!--フォロー機能ここまで-->
                <td>
                  <%= link_to "Show", user_path(user.id) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
  
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
<table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th clspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag @user, :profile_image, size: '40x40', format: 'jpeg', fallback:"no_image.jpg" %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <!--フォロー数・フォロワー数表示とフォローするor外すの表示と機能-->
                <td>
                  フォロー数<%= user.followings.count %>
                </td>
                <td>
                  フォロワー数<%= user.followers.count %>
                </td>
                <td>
                  <% if current_user != user %>
                    <% if user.followed_by?(current_user) %>
                    <%= link_to "フォロー外す",user_relationships_path(user.id),method: :delete %>
                    <% else %>
                    <%= link_to "フォローする",user_relationships_path(user.id),method: :post %>
                    <% end %>
                  <% end %>
                </td>
                <!--フォロー機能ここまで-->
                <td>
                  <%= link_to "Show", user_path(user.id) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
  
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_list2.html.erb
      <div class="row">
        <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill,100,100,format: 'jpeg', fallback:"no_image.jpg" %>
         <table class="table">
           <tbody>
             <tr>
               <th>name</ty>
               <th><%= user.name %></th>
             </tr>
             <tr>
               <th>introduction</th>
               <th><%= user.introduction %></th>
             </tr>
             <!--フォロー・フォロワー数表示とフォローするorフォロー外すボタン-->
             <tr>
                 <th>follows</th>
                 <th><%= link_to user.followings.count,user_followings_path(user.id) %></th>
             </tr>
             <tr>
                 <th>followers</th>
                 <th><%= link_to user.followers.count,user_followers_path(user.id) %></th>
             </tr>
             
              
             
           </tbody>
         </table>
         <div class="row">
             <% if current_user != user %>
                <% if user.followed_by?(current_user) %>
                  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
                <% end %>
              <% else %>
                <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
              <% end %>

         </div>
         <h2 class="mt-3">New book</h2>
         <%= form_with model:new_book, local:true do |f| %>
         <div class="field">
             <label>Title</label><br>
             <%= f.text_field :title %>
         </div>
         <div class="field">
             <label>Opinion</label><br>
             <%= f.text_field :body %>
         </div>
         <div class="action">
         <%= f.submit 'Create Book', class: 'btn btn-success' %>
         <% end %>
         </div>
      </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User info</h1>
       <% if @user.errors.any? %>
        <div class="error">
         <%= @user.errors.count %>errors prohibited this obj from being saved:
         <% @user.errors.full_messages.each do |message| %>
         <ul>
             <li>
                 <%= message %>
             </li>
         </ul>
          <% end %>
        <% end %>
        <%= form_with model:@user, local:true do |f| %>
        <div class="field">
         <label>Name</label><br>
         <%= f.text_field :name %>
        </div>
        <div class="field">
          <label>Image</label><br>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        </div>
        <div class="field">
        <label>Introduction</label><br>
         <%= f.text_field :introduction %>
        </div>
        <div action="action">
         <%= f.submit 'Update User', class: 'btn btn-secondary' %><br>
         <% end %>
       </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
      <%= render 'books/error',book: @book %>
      <%= render 'books/list',user: @user,new_book: @book %>

      <div class="col-md-8 offset-md-1">
          <h2>Users</h2>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th clspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag @user, :profile_image, size: '40x40', format: 'jpeg', fallback:"no_image.jpg" %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td>
                  <%= link_to "Show", user_path(user.id) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
  </div>
  </div>

app/views/users/show.html.erb
 <p class="flash">
   <%= flash[:update] %>
   <%= notice %>
 </p>
      <%= render 'books/error',book: @book %>
      <%= render 'list2',user: @user,new_book: @book %>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, size: '40x40', format: 'jpeg', fallback:"no_image.jpg" %><br>
                  <% end %>
                </td>
                <td>
                  <%= link_to book.title, book_path(book.id) %>
                </td>
                <td><%= book.body %></td>
                <td>コメント数<%= book.book_comments.count %></td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>