config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about" , as: "about"
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
   resource :favorites, only: [:create, :destroy]
   
   resources :book_comments, only: [:create, :destroy]
  end
  
    resources :users, only: [:show, :new, :create, :edit, :update, :index] do
        # フォロー機能追加に伴い以下3行追加
      resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user

has_many :favorites, dependent: :destroy
has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

validates :title, presence: true
validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, length: { minimum: 1}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comment, dependent: :destroy

  attachment :profile_image
  
  # フォローしているユーザとのアソシエイト
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  # 
  
  # フォローされているユーザーとのアソシエイト
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  # 
  # ユーザーをフォローする時既にフォローしていないか
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
  # 
  
  validates :name, presence: true, uniqueness: true, length:{ minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top,:about]


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end


  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
      devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
    end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.book_id = book.id
    comment.user_id = current_user.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment .find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(@book)
  end

  private
    def book_comment_params
      params.require(:book_comment).permit(:comment)

    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController



  def index
    @books = Book.all
    @book = Book.new
    @user = current_user

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id)
    flash[:create] = 'You have created book successfully.'
    else
    @books = Book.all
    @user = current_user
    render :index
    end
  end



  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
     @book.destroy
    redirect_to books_path

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:update] = 'You have updated book successfully.'
    else
      render :edit

    end

  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_back(fallback_location: root_path)

  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id)
    flash[:create] = 'You have created book successfully.'
    else
    @books = Book.all
    render :index
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end


  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:update] = "You have updated user successfully."
    else
      render :edit
    end
  end
  
  
  def follows
    user = User.find(params[:id])
    @users = user.followers
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-1g navbar-dark bg-dark">
      <div class="container">

        <%= link_to "Bookers", root_path %>

        <% if user_signed_in? %>
          <ul class="m1-auto">
            <li class="nav-list-item">
              <i class="fas fa-home"></i>
              <%= link_to "Home", user_path(current_user) %>
            </li>
            <li class="nav-list-item">
              <i class="fas fa-users"></i>
              <%= link_to "Users", users_path %>
            </li>
            <li class="nav-list-item">
              <i class="fas fa-book-open"></i>
              <%= link_to "Books", books_path %>
            </li>
            <li class="nav-list-item">
              <i class="fas fa-sign-out-alt"></i>
              <%= link_to "logout", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
            <% else %>
          <ul>
            <li class="nav-list-item">
              <i class="fas fa-home"></i>
              <%= link_to "Home", root_path %>
            </li>
            <li class="nav-list-item">
              <i class="fas fa-link"></i>
              <%= link_to "About", about_path %>
            </li>
            <li class="nav-list-item">
              <i class="fas fa-user-plus"></i>
              <%= link_to "sign up", new_user_registration_path %>
            </li>
            <li class="nav-list-item">
              <i class="fas fa-sign-in-alt"></i>
              <%= link_to "login", new_user_session_path %>
            </li>
          </ul>
      </div>
    </nav>
    <% end %>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>


  </body>
</html>